# compose.yaml (preferred over docker-compose.yml)
services:
  orders-service:
    build:
      context: .              # Context should be the root of the solution
      dockerfile: Reto2/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  pagos-service:
    build:
      context: .              # Context should be the root of the solution
      dockerfile: Pagos/PagosApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    container_name: demo-rabbit    
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
